### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by moos3** [poise/application_git#7]
Is it possible to do a branch checkout when calling using this?

**Comment by coderanger** [comment]
Yes, same as with the core git resource. Use the ref/tag/branch property.

On July 27, 2016 at 12:53:35 PM PDT, Richard notifications@github.com wrote:Is it possible to do a branch checkout when calling using this?  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
